### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/getting-started-with-guis#10]
- Merge step 3 'What is a GUI' into step 1 as introduction
- There are collapsible sections in step 6 and step 8 which could be hints. Or is this a case of not using hints in case it puts beginners off?
- In the last step, add a link to the guizero documentation and suggest that learners explore more of the widgets?

**Comment by martinohanlon** [comment]
Thanks, I have made some changes:
 - I havent merged step 3 with 1 as to keep consistency with other projects, and not overwhelm the learner
 - I have made step 8 into a hint, it made sense, I left step 6 as a collapse as I want to give the opportunity to new learners to 'see it all'.
 - good idea, ive added links to guizero docs
